### PR TITLE
Test fixes, labValidator fix

### LINKED ISSUE #166: [FEATURE] Automated Testing v2

### PR DESCRIPTION
**Pull request by cemersoz**
#166

### CODE REVIEW

File: client/imports/ui/pages/lab/labview.ts [hunk 1]
```diff
@@ -107,11 +107,11 @@ export default class LabView extends MeteorComponent {
       }
       else{
         if(res.verified){
```
Comment (DerekTBrown) [inline client/imports/ui/pages/lab/labview.ts]: Indentation

File: client/imports/ui/pages/lab/labview.ts [hunk 2]
```diff
@@ -121,19 +121,19 @@ export default class LabView extends MeteorComponent {
...
+     Meteor.call('nextTask',"1",function(err,res){
+       if(err){
+	 slf.nextButton = false;
+         console.log("try again");
+       }
+       else{
+         console.log(res);
+         slf.tasks = res.taskList
+         slf.toTask(slf.tasks[res.taskNo-1]);
+	 slf.labProgress = res.taskNo+" / "+slf.tasks.length
```
Comment (DerekTBrown) [inline client/imports/ui/pages/lab/labview.ts]: Indentation

File: client/imports/ui/pages/lab/labview.ts [hunk 3]
```diff
@@ -121,19 +121,19 @@ export default class LabView extends MeteorComponent {
...
-        slf.taskUpdates = res.taskUpdates;
-      }
-    });
+     Meteor.call('nextTask',"1",function(err,res){
+       if(err){
+	 slf.nextButton = false;
+         console.log("try again");
+       }
+       else{
+         console.log(res);
```
Comment (DerekTBrown) [inline client/imports/ui/pages/lab/labview.ts]: Please use proper I/O

File: client/imports/ui/pages/lab/labview.ts [hunk 4]
```diff
@@ -121,19 +121,19 @@ export default class LabView extends MeteorComponent {
...
-        slf.tasks = res.taskList
-        slf.toTask(slf.tasks[res.taskNo-1]);
-        slf.labProgress = res.taskNo+" / "+slf.tasks.length;
-        slf.taskUpdates = res.taskUpdates;
-      }
-    });
+     Meteor.call('nextTask',"1",function(err,res){
+       if(err){
+	 slf.nextButton = false;
+         console.log("try again");
```
Comment (DerekTBrown) [inline client/imports/ui/pages/lab/labview.ts]: Please use proper I/O

File: collections/labs.ts [hunk 5]
```diff
@@ -54,7 +51,7 @@ labs.allow({
         },
         course_id: {
           type: String,
-          regEx: SimpleSchema.RegEx.Id,
+          /*regEx: SimpleSchema.RegEx.Id,*/
```
Comment (DerekTBrown) [inline collections/labs.ts]: Why this no work?

File: server/imports/lab/checkLab.js [hunk 6]
```diff
@@ -1,21 +1,45 @@
...
-  }
+
+  if(!str) {
+    TuxLog.log("warn", "labfile is null");
+    return false; 
+  } //check for file import
   else{
-    return tux.titleList;
+    try{
+      var tux = eval(str);
```
Comment (DerekTBrown) [inline server/imports/lab/checkLab.js]: Tux isn't a semantic name for this

File: server/imports/startup/index.js [hunk 7]
```diff
@@ -15,3 +15,5 @@ import './methods.js'
 
 // Start Cache
 import './cache.js'
+
+async = require('async')
```
Comment (DerekTBrown) [inline server/imports/startup/index.js]: Put this in the top of the file.  We will also need to refactor existing code to use this global call to avoid needless collisions.

File: tests/example_data/labs/labs.bad.js [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
...ction(env){\n    return env.start();\n  }\n  var v2 = function(env){\n    return env.start();\n  }\n  var s3 = function(env){\n    return env.start();\n  }\n  var v3 = function(env){\n    return env.start();\n  }\n  var s4 = function(env){\n    return env.start();\n  }\n  var v4 = function(env){\n    return env.start();\n  }\n  /* @task1 this is task 1 \n   tomato{}  \n   hi();\n    @onevar1\n   I\'m a cheesepuff\n   @othervar1\n  */\n  var task1 = tuxlab.newTask(\'TASK1\',\'MD1\',s1,v1)\n  /*\n@task2\nthis is task 2 \n   potato{}  \n   bye();\n    @onevar2\n   I\'m a cheesepuff\n   @anothervar2\n  */\n  var task2 = tuxlab.newTask(\'TASK2\',\'MD2\',s2,v2)\n  /*@task3 this is task 3\n   onion{}  \n   later();\n    @onevar3\n   I\'m a cheesepuff\n   @othervar3\n  */\n  var task3 = tuxlab.newTask(\'TASK3\',\'MD3\',s3,v3)\n  /*\n   @task4 this is task 4\n   turnip{}  \n   ello();\n    @onevar4\n   I\'m a cheesepuff\n   @othervar4\n  */\n  var task4 = tuxlab.newTask(\'TASK4\',\'MD4\',s4,v4)\n  return tuxlab.init()\n           .nextTask(task1)\n           .nextTask(task2)\n           .nextTask(task3)\n           .nextTask(task4);\n}\n//export modified tuxlab\nmodule.exports = tuxlab;\n';
```
Comment (DerekTBrown) [inline tests/example_data/labs/labs.bad.js]: This is ugly af

File: tests/example_data/labs/labs.good.js [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
...ction(env){\n    return env.start();\n  }\n  var v2 = function(env){\n    return env.start();\n  }\n  var s3 = function(env){\n    return env.start();\n  }\n  var v3 = function(env){\n    return env.start();\n  }\n  var s4 = function(env){\n    return env.start();\n  }\n  var v4 = function(env){\n    return env.start();\n  }\n  /* @task1 this is task 1 \n   tomato{}  \n   hi();\n    @onevar1\n   I\'m a cheesepuff\n   @othervar1\n  */\n  var task1 = tuxlab.newTask(\'TASK1\',\'MD1\',s1,v1)\n  /*\n@task2\nthis is task 2 \n   potato{}  \n   bye();\n    @onevar2\n   I\'m a cheesepuff\n   @anothervar2\n  */\n  var task2 = tuxlab.newTask(\'TASK2\',\'MD2\',s2,v2)\n  /*@task3 this is task 3\n   onion{}  \n   later();\n    @onevar3\n   I\'m a cheesepuff\n   @othervar3\n  */\n  var task3 = tuxlab.newTask(\'TASK3\',\'MD3\',s3,v3)\n  /*\n   @task4 this is task 4\n   turnip{}  \n   ello();\n    @onevar4\n   I\'m a cheesepuff\n   @othervar4\n  */\n  var task4 = tuxlab.newTask(\'TASK4\',\'MD4\',s4,v4)\n  return tuxlab.init()\n           .nextTask(task1)\n           .nextTask(task2)\n           .nextTask(task3)\n           .nextTask(task4);\n}\n//export modified tuxlab\nmodule.exports = tuxlab;\n';
```
Comment (DerekTBrown) [inline tests/example_data/labs/labs.good.js]: this is also ugly af
